# render.yaml - Configuration for deploying ShopperGPT on Render

services:
  # Web Service (FastAPI application)
  - type: web
    name: shoppergpt-api
    env: python
    region: frankfurt # Choose a region close to you or your users, e.g., oregon, frankfurt, singapore
    plan: free # Use the free instance type
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python src/db_manager.py" # Install dependencies and initialize DB (if needed)
    startCommand: "uvicorn src.main:app --host 0.0.0.0 --port $PORT --app-dir /opt/render/project/src/shoppergpt" # Use $PORT provided by Render
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Specify the Python version used
      - key: DATABASE_URL
        fromDatabase:
          name: shoppergpt-db # Name of the database service defined below
          property: connectionString # Use the connection string provided by Render
      - key: OPENAI_API_KEY
        sync: false # Keep secret, set in Render dashboard
      - key: WHATSAPP_API_TOKEN
        sync: false # Keep secret, set in Render dashboard
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false # Keep secret, set in Render dashboard
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false # Keep secret, set in Render dashboard
      - key: ADMIN_USERNAME
        sync: false # Keep secret, set in Render dashboard
      - key: ADMIN_PASSWORD
        sync: false # Keep secret, set in Render dashboard
    autoDeploy: yes # Automatically deploy when pushing to the connected GitHub branch (e.g., main)

  # Database Service (PostgreSQL - Free tier available)
  - type: postgres
    name: shoppergpt-db
    region: frankfurt # Use the same region as the web service
    plan: free # Use the free database plan (limited resources)
    # postgresqlMajorVersion: 14 # Specify PostgreSQL version if needed, defaults to latest available
    # diskGiB: 1 # Specify disk size for paid plans

